### ISSUE TITLE
Switch from spinner to loading indicator

### ISSUE THREAD

**Issue by ledpup** [ledpup/ClimateExplorer#231]
https://blazorise.com/docs/extensions/loadingindicator

**Comment by snehalchaudhari98** [comment]
Hey @ledpup, I'm new to the community, and I'm interested in working on this issue. If this issue isn't assigned to a contributor, I'd like to work on it.

**Comment by ledpup** [comment]
Hi guys, I tried to have a go at this but the CSS is messed up. Functionally it's okay. There is bit of commented code that would need to be uncommented after the CSS is fixed.

Branch is: issues/231-loadingindicator

**Comment by snehalchaudhari98** [comment]
hey @ledpup , could you provide some steps on how to get started on this issue after the setup?

**Comment by ledpup** [comment]
> hey @ledpup , could you provide some steps on how to get started on this issue after the setup?

Hi @snehalchaudhari98, if you follow the setup with the branch I mentioned in the comments, you should see the page load up with the map, location info and the chart. Below the cart the loading indicator will be spinning around. But it's in the wrong place; it needs to be spinning overlayed on top of the chart with the chart greyed out underneath. I think it's how the flex in the css is setup that is messing it up.

If you look at the example they have on the blazorise webpage, that's how I want it to look. In their example they have the chart with the loading indicator wrapped around it. I did the same thing on the climate explorer chart, but yeah, didn't just work out of the box, unfortunately.

**Comment by inifnite** [comment]
Someone working on this?

**Comment by ledpup** [comment]
Hi @inifnite, I haven't heard from @snehalchaudhari98. Happy for you to look at it.

**Comment by inifnite** [comment]
I tried running the project on my machine but on the webpage it says "An unhandled error has occurred" 
<img width="1624" alt="Screenshot 2023-07-17 at 12 36 16 PM" src="https://github.com/ledpup/ClimateExplorer/assets/45487930/21e0b0a7-3eac-412b-93de-d595b112269e">

**Comment by ledpup** [comment]
Hi @inifnite, can you try running it again? The first time you run it it has to cache a lot of data. It can take a minute or so to build that cache. 

Sometimes when you run first time it gets into a concurrency issue. That might actually be fixed now on the master branch as I fixed a long existing double-request bug (whoops).

**Comment by ledpup** [comment]
@inifnite can you open dev tools and get the console error if it's still happening? I'll create a bug for it. Could also be some sort of permissions issue. It has to be able to write to the file system on the web api to be able to cache.

**Comment by inifnite** [comment]
I tried with the master branch with sudo but it stills have the error. I am attaching the screenshot of the log.
<img width="1624" alt="Screenshot 2023-07-18 at 11 36 07 AM" src="https://github.com/ledpup/ClimateExplorer/assets/45487930/c2405407-5ede-4745-b7eb-c667d6a43407">

**Comment by ledpup** [comment]
Oh, a CORS block. That's supposed to just allow everything through but I have seen it not work. I'll look into it.

**Comment by ledpup** [comment]
Hi @inifnite I can't reproduce that issue unless I remove **builder.AllowAnyOrigin();** from Program.cs in the WebApi project.

After reading the docs, I found another cors setting I could add. Maybe try the branch below. I'll add it into master if it works for you.

https://github.com/ledpup/ClimateExplorer/tree/issues/cors-AllowAnyMethod

**Comment by inifnite** [comment]
Its machine issue, I am working on mac which has '\' indentation for filesystem but the project has windows indentation ('/').

**Comment by inifnite** [comment]
Hi @ledpup, adding `<link href="_content/Blazorise.LoadingIndicator/blazorise.loadingindicator.css" rel="stylesheet" />`  just below spinkit.css (line 68, branch -> issue/231) in ClimateExplorer\ClimateExplorer.Visualiser\wwwroot\index.html worked for me.

**Comment by ledpup** [comment]
It's there in the documentation! I guess I should have read it properly. Nice one!
