### ISSUE TITLE
Modal does a strange page width change when there is a scrollbar on the screen already

### ISSUE THREAD

**Issue by ledpup** [ledpup/ClimateExplorer#300]
![image](https://github.com/ledpup/ClimateExplorer/assets/1639322/4d6d847e-cc24-4b5c-a869-bef2f1823a94)

**Comment by stsrki** [comment]
I'm not able to reproduce this. I'm trying it on BS4 and BS5 with the scrollbar visible on the screen.

Do you have anything else in your project that might affect the modal?

**Comment by ledpup** [comment]
> I'm not able to reproduce this. I'm trying it on BS4 and BS5 with the scrollbar visible on the screen.
> 
> Do you have anything else in your project that might affect the modal?

Thanks @stsrki, I'll keep looking into it.
